### ISSUE TITLE
New HA core Beta causing issues

### ISSUE THREAD

**Issue by grantclem** [zweckj/lamarzocco#26]
Installed the latest HA core beta and have run into the issues with this CC.

Not sure if it is related to what is mentioned at the bottom of this page?

https://rc.home-assistant.io/blog/2023/12/27/release-20241/

```
Logger: homeassistant.setup
Source: setup.py:403
First occurred: 09:01:34 (6 occurrences)
Last logged: 09:01:34

Unable to prepare setup for platform 'lamarzocco.button': Platform not found (Exception importing custom_components.lamarzocco.button).
Unable to prepare setup for platform 'lamarzocco.sensor': Platform not found (Exception importing custom_components.lamarzocco.sensor).
Unable to prepare setup for platform 'lamarzocco.switch': Platform not found (Exception importing custom_components.lamarzocco.switch).



```
Logger: homeassistant.loader
Source: loader.py:842
First occurred: 09:01:34 (6 occurrences)
Last logged: 09:01:34

Unexpected exception importing platform custom_components.lamarzocco.button
Unexpected exception importing platform custom_components.lamarzocco.sensor
Unexpected exception importing platform custom_components.lamarzocco.switch
Unexpected exception importing platform custom_components.lamarzocco.update
Unexpected exception importing platform custom_components.lamarzocco.water_heater
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 842, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 859, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/lamarzocco/binary_sensor.py", line 28, in <module>
    @dataclass
     ^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1230, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1220, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1027, in _process_class
    _init_fn(all_init_fields,
  File "/usr/local/lib/python3.11/dataclasses.py", line 545, in _init_fn
    raise TypeError(f'non-default argument {f.name!r} '
TypeError: non-default argument 'extra_attributes' follows default argument
```

Unable to prepare setup for platform 'lamarzocco.update': Platform not found (Exception importing custom_components.lamarzocco.update).
Unable to prepare setup for platform 'lamarzocco.water_heater': Platform not found (Exception importing custom_components.lamarzocco.water_heater).
```

**Comment by zweckj** [comment]
fixed in [v0.13.2b1](https://github.com/zweckj/lamarzocco/releases/tag/v0.13.2b1)
