### ISSUE TITLE
Integration stopped working

### ISSUE THREAD

**Issue by gmathur** [zweckj/lamarzocco#34]
Started seeing this error today after I upgraded to core preview. Tried downgrading subsequently but that didn't seem to help either.

Logger: homeassistant.components.lamarzocco.coordinator
Source: helpers/update_coordinator.py:313
Integration: La Marzocco (documentation, issues)
First occurred: 10:50:53 PM (3 occurrences)
Last logged: 10:51:03 PM

Unexpected error fetching lamarzocco data: 'machine'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 313, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/lamarzocco/coordinator.py", line 43, in _async_update_data
    await self._async_init_client()
  File "/usr/src/homeassistant/homeassistant/components/lamarzocco/coordinator.py", line 59, in _async_init_client
    machine_serial=self.config_entry.data[CONF_MACHINE],
                   ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'machine'

**Comment by zweckj** [comment]
To cite from the big red warning in the release notes: 

> [!CAUTION]
> To install this release you need to first remove your current installation
