### ISSUE TITLE
2024.12 breaks lamarzocco integration

### ISSUE THREAD

**Issue by Dual-0** [zweckj/lamarzocco#44]
Hi, i updated to HA [2024.12](https://www.home-assistant.io/blog/2024/12/04/release-202412/) and got this error:

```
Logger: homeassistant.setup
Quelle: setup.py:334
Erstmals aufgetreten: 11:41:23 (1 Vorkommnisse)
Zuletzt protokolliert: 11:41:23

Setup failed for custom integration 'lamarzocco': Unable to import component: No module named 'lmcloud'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1034, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1014, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1074, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/lamarzocco/__init__.py", line 9, in <module>
    from .coordinator import LmApiCoordinator
  File "/config/custom_components/lamarzocco/coordinator.py", line 5, in <module>
    from lmcloud.exceptions import AuthFail, RequestNotSuccessful
ModuleNotFoundError: No module named 'lmcloud'
```

**Comment by zweckj** [comment]
The custom integration is deprecated, switch to the built-in integration instead.
